-- SPDX-FileCopyrightText: 2026 Alexandra de Wit
--
-- SPDX-License-Identifier: MIT

{- | Prepared corpus inputs for ecosystem-neutral benchmark groups.
The shared adapter record owns the wire bytes and their format-specific operations.
-}
module Ecluse.Bench.Corpus (
    LoadedEntry,
    entryInfo,
    entryName,
    syntheticInput,
    syntheticPackageInfo,
    benchEvalContext,
    benchRules,
) where

import Data.Time (UTCTime (UTCTime), fromGregorian, nominalDay, secondsToDiffTime)
import Ecluse.Core.Package (PackageInfo, mkScope)
import Ecluse.Core.Registry.CachedDocument (CachedDoc)
import Ecluse.Core.Registry.Metadata (MetadataError)
import Ecluse.Core.Rules.Types (EvalContext (EvalContext), PrecededRule, Rule (AllowIfOlderThan, AllowScope, DenyInstallTimeExecution))
import Ecluse.Core.Snapshot (Snapshot (Snapshot), digestOf)
import Ecluse.Test.Corpus (CorpusTier (Heavy, Large, Medium), cpName, cpTier)
import Ecluse.Test.EcosystemBench.Types (EcosystemBench (..), LoadedEntry)
import Ecluse.Test.Rules (atDefaultPrecedence)

-- | The projection validated when the corpus loaded.
entryInfo :: LoadedEntry -> PackageInfo
entryInfo (_, _, info, _) = info

-- | A package identity and its declared corpus size tier.
entryName :: LoadedEntry -> String
entryName (package, _, _, _) = toString (cpName package) <> " (" <> tierName (cpTier package) <> ")"
  where
    tierName = \case
        Medium -> "medium"
        Large -> "large"
        Heavy -> "heavy"

-- | Prepare synthetic serving inputs with the digest of the exact generated bytes.
syntheticInput :: EcosystemBench -> Int -> Either MetadataError (Snapshot CachedDoc, PackageInfo)
syntheticInput ecosystem count = do
    let raw = ebSynthetic ecosystem count
    (info, document) <- ebProject ecosystem (ebSyntheticName ecosystem) raw
    pure (Snapshot (digestOf raw) document, info)

-- | Project a generated byte document through the registered adapter.
syntheticPackageInfo :: EcosystemBench -> Int -> Either MetadataError PackageInfo
syntheticPackageInfo ecosystem = fmap snd . syntheticInput ecosystem

-- | A fixed clock makes age-based rule measurements repeatable.
benchEvalContext :: EvalContext
benchEvalContext = EvalContext (UTCTime (fromGregorian 2026 6 27) (secondsToDiffTime 0)) Nothing

-- | Exercise all three pure rule types over each projected release.
benchRules :: [PrecededRule]
benchRules =
    [ atDefaultPrecedence (AllowScope (mkScope "trusted-scope"))
    , atDefaultPrecedence DenyInstallTimeExecution
    , atDefaultPrecedence (AllowIfOlderThan (30 * nominalDay))
    ]
