#!/usr/bin/env bash
#
# Regenerate the version-ordering differential-test fixtures from the canonical
# reference implementations:
#
#   * npm      -> node-semver           (semver.compare)
#   * PyPI     -> Python `packaging`    (packaging.version.Version)
#   * RubyGems -> Ruby `Gem::Version`   (built in)
#
# The output is committed and consumed by the PURE, GATING unit test
# (test/unit/Ecluse/VersionOrderingSpec.hs). This script needs the reference
# tools — the Nix dev shell provides them — and is run only when the curated
# version lists below change. The same comparisons are re-checked live (against
# whatever tools are installed) by the non-gating smoke test; see
# docs/architecture/domain-model.md -> "Internal Domain Model".
#
# Usage:  make gen-version-fixtures   (runs inside the Nix dev shell)
#
# Fixture line format (one comparison per line):  ECOSYSTEM|A|B|ORD
# where ORD is LT | EQ | GT, the ordering of A relative to B.
#
set -euo pipefail

out="${1:-test/unit/fixtures/version-ordering.txt}"
mkdir -p "$(dirname "$out")"

# Curated version lists chosen to exercise the fiddly corners of each grammar:
# numeric ordering (10 vs 9), prerelease vs release, the per-ecosystem
# prerelease tie-break rules, and non-canonical spellings.
npm_versions=(
  0.0.1 0.1.0 1.0.0 1.0.1 1.1.0 1.9.0 1.10.0 2.0.0 9.9.9 10.0.0
  1.0.0-0 1.0.0-1 1.0.0-1.2 1.0.0-alpha 1.0.0-alpha.1 1.0.0-alpha.beta
  1.0.0-beta 1.0.0-beta.2 1.0.0-beta.11 1.0.0-rc.1 1.0.0+build
)
pypi_versions=(
  1.0 1.0.0 1.0.0.0 1.0.1 1.1 1.9 1.10 2.0
  1.0a1 1.0a2 1.0b1 1.0rc1 1.0.dev1 1.0.post1
  1.0a1.dev1 1.0.post1.dev1 1.0alpha1 1.0-1 1!1.0
)
rubygems_versions=(
  0.9.0 1.0 1.0.0 1.0.0.0 1.0.1 1.1.0 1.9.0 1.10.0 2.0.0
  1.0.0.alpha 1.0.0.beta1 1.0.0.beta2 1.0.0.pre 1.0.0.pre.1
)

ord() { case "$1" in -1) echo LT ;; 0) echo EQ ;; *) echo GT ;; esac; }

emit_npm() {
  node - "$@" <<'JS'
const semver = require("semver");
const vs = process.argv.slice(2);
for (const a of vs) for (const b of vs) {
  console.log(`npm|${a}|${b}|${semver.compare(a, b)}`);
}
JS
}

emit_pypi() {
  python3 - "$@" <<'PY'
import sys
from packaging.version import Version
vs = sys.argv[1:]
for a in vs:
    for b in vs:
        A, B = Version(a), Version(b)
        print(f"pypi|{a}|{b}|{(A > B) - (A < B)}")
PY
}

emit_rubygems() {
  ruby - "$@" <<'RB'
vs = ARGV
vs.each do |a|
  vs.each do |b|
    puts "rubygems|#{a}|#{b}|#{Gem::Version.new(a) <=> Gem::Version.new(b)}"
  end
end
RB
}

{
  echo "# Generated by scripts/gen-version-fixtures.sh from the reference"
  echo "# implementations (node-semver / Python packaging / Ruby Gem::Version)."
  echo "# Do not edit by hand; rerun the script. Format: ECOSYSTEM|A|B|ORD"
  emit_npm "${npm_versions[@]}"       | while IFS='|' read -r e a b n; do echo "$e|$a|$b|$(ord "$n")"; done
  emit_pypi "${pypi_versions[@]}"     | while IFS='|' read -r e a b n; do echo "$e|$a|$b|$(ord "$n")"; done
  emit_rubygems "${rubygems_versions[@]}" | while IFS='|' read -r e a b n; do echo "$e|$a|$b|$(ord "$n")"; done
} > "$out"

echo "wrote $(grep -vc '^#' "$out") comparisons to $out"
